export default {
    "data":{
        "currency": [
            "USD",
            "AED",
            "AFN",
            "ALL",
            "AMD",
            "ANG",
            "AOA",
            "ARS",
            "AUD",
            "AWG",
            "AZN",
            "BAM",
            "BBD",
            "BDT",
            "BGN",
            "BIF",
            "BMD",
            "BND",
            "BOB",
            "BRL",
            "BSD",
            "BWP",
            "BZD",
            "CAD",
            "CDF",
            "CHF",
            "CLP",
            "CNY",
            "COP",
            "CRC",
            "CVE",
            "CZK",
            "DJF",
            "DKK",
            "DOP",
            "DZD",
            "EGP",
            "ETB",
            "EUR",
            "FJD",
            "FKP",
            "GBP",
            "GEL",
            "GIP",
            "GMD",
            "GNF",
            "GTQ",
            "GYD",
            "HKD",
            "HNL",
            "HRK",
            "HTG",
            "HUF",
            "IDR",
            "ILS",
            "INR",
            "ISK",
            "JMD",
            "JPY",
            "KES",
            "KSG",
            "KHR",
            "KMF",
            "KRW",
            "KYD",
            "KZT",
            "LAK",
            "LBP",
            "LKR",
            "LRD",
            "LSL",
            "MAD",
            "MDL",
            "MGA",
            "MKD",
            "MMK",
            "MNT",
            "MOP",
            "MRO",
            "MUR",
            "MVR",
            "MWK",
            "MXN",
            "MYR",
            "MZN",
            "NAD",
            "NGN",
            "NIO",
            "NOK",
            "NPR",
            "NZD",
            "PAB",
            "PEN",
            "PGK",
            "PHP",
            "PKR",
            "PLN",
            "PYG",
            "QAR",
            "RON",
            "RSD",
            "RUB",
            "RWF",
            "SAR",
            "SBD",
            "SCR",
            "SEK",
            "SGD",
            "SHP",
            "SLL",
            "SOS",
            "SRD",
            "STD",
            "SVC",
            "SZL",
            "THB",
            "TJS",
            "TOP",
            "TRY",
            "TTD",
            "TWD",
            "TZS",
            "UAH",
            "UGX",
            "UYU",
            "UZS",
            "VND",
            "VUV",
            "WST",
            "XAF",
            "XCD",
            "XOF",
            "XPF",
            "YER",
            "ZAR",
            "ZMW"
          ],
        "products": [
          {
            "image_url": "https://d1b929y2mmls08.cloudfront.net/luminskin/img/new-landing-page/moisturizing-balm.png",
            "id": 3,
            "title": "Premium-Grade Moisturizing Balm",
            "price": 20,
          },
          {
            "image_url": "https://d1b929y2mmls08.cloudfront.net/luminskin/img/new-landing-page/charcoal-cleanser.png",
            "id": 2,
            "title": "No-Nonsense Charcoal Cleanser",
            "price": 20,
          },
          {
            "image_url": "https://i.shgcdn.com/b44f5ef8-6bc0-4a4a-8eef-1f7ced30503d/-/format/auto/-/preview/3000x3000/-/quality/lighter/",
            "id": 42,
            "title": "Clarifying Body Wash",
            "price": 20,
          },
          {
            "image_url": "https://i.shgcdn.com/4c9671b2-8161-4e58-b3b5-cefa74b74a05/-/format/auto/-/preview/3000x3000/-/quality/lighter/",
            "id": 39,
            "title": "Keratin Recovery Shampoo",
            "price": 20,
          },
          {
            "image_url": "https://i.shgcdn.com/aaef22bc-bf48-4e0d-81c2-482265460220/-/format/auto/-/preview/3000x3000/-/quality/lighter/",
            "id": 40,
            "title": "Keratin Strengthening Conditioner",
            "price": 20,
          },
          {
            "image_url": "https://i.shgcdn.com/f1ae9d7a-ca43-4a2d-a5cf-c45506a47708/-/format/auto/-/preview/3000x3000/-/quality/lighter/",
            "id": 41,
            "title": "Advanced Repair Scalp Treatment",
            "price": 20,
          },
          {
            "image_url": "https://d1b929y2mmls08.cloudfront.net/luminskin/img/new-landing-page/dark-circle-defense.png",
            "id": 14,
            "title": "Dark Circle Defense",
            "price": 20,
          },
          {
            "image_url": "https://d1b929y2mmls08.cloudfront.net/luminskin/img/new-landing-page/face-mask.jpg",
            "id": 47,
            "title": "Intensive Repair Face Mask",
            "price": 20,
          },
          {
            "image_url": "https://d1b929y2mmls08.cloudfront.net/luminskin/img/new-landing-page/eye-patch.png",
            "id": 43,
            "title": "Anti-Fatigue Eye Patch",
            "price": 20,
          },
          {
            "image_url": "https://d1b929y2mmls08.cloudfront.net/luminskin/img/new-landing-page/anti-wrinkle-serum.png",
            "id": 12,
            "title": "Anti-Wrinkle Defense",
            "price": 20,
          },
          {
            "image_url": "https://d1b929y2mmls08.cloudfront.net/luminskin/img/new-landing-page/reload-exfoliating-rub.png",
            "id": 4,
            "title": "Reload Exfoliating Rub",
            "price": 20,
          },
          {
            "image_url": "https://d1b929y2mmls08.cloudfront.net/luminskin/img/new-landing-page/pore-strip.png",
            "id": 44,
            "title": "Charcoal Cleansing Pore Strip",
            "price": 20,
          },
          {
            "image_url": "https://d1b929y2mmls08.cloudfront.net/luminskin/img/new-landing-page/age-management.png",
            "id": 10,
            "title": "Age Management Collection",
            "price": 20,
          },
          {
            "image_url": "https://d1b929y2mmls08.cloudfront.net/luminskin/img/new-landing-page/classic-maintenance.png",
            "id": 13,
            "title": "Classic Maintenance",
            "price": 20,
          },
          {
            "image_url": "https://d1b929y2mmls08.cloudfront.net/luminskin/img/new-landing-page/correction-trio.png",
            "id": 25,
            "title": "Correction Trio Collection",
            "price": 20,
          },
          {
            "image_url": "https://d1b929y2mmls08.cloudfront.net/luminskin/img/new-landing-page/all-products.png",
            "id": 36,
            "title": "The Complete Skincare Gift Set",
            "price": 20,
          },
          {
            "image_url": "https://d1b929y2mmls08.cloudfront.net/luminskin/img/new-landing-page/recovery-oil.png",
            "id": 7,
            "title": "After Hours Recovery Oil",
            "price": 20,
          },
          {
            "image_url": "https://d1b929y2mmls08.cloudfront.net/luminskin/img/new-landing-page/deflator.png",
            "id": 45,
            "title": "Eye Depuffer",
            "price": 20,
          },
          {
            "image_url": "https://d1b929y2mmls08.cloudfront.net/luminskin/img/new-landing-page/face-mist.png",
            "id": 46,
            "title": "Hydrating Mist Spray",
            "price": 20,
          }        
        ],
    }
};
  